#!/bin/sh
#
#

umask 077

start() {
	echo "Setting time..."
	(while ! /usr/bin/ntpdate -s time.nist.gov; do sleep 3; done) &
}
stop() {
	echo "S99zz stop"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo $"Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
